include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
linter:
  rules:
    no_leading_underscores_for_local_identifiers: false
    unawaited_futures: true
